<?php
$razze=array(
'nome'=>array(1=>$lang['Umani'],2=>$lang['Elfi'],3=>$lang['Non_morti'],4=>$lang['Orchi'],5=>$lang['Nani']),
'descrizione'=>array(1=>$lang['desc_umani'],2=>$lang['desc_elfi'],3=>$lang['desc_non_morti'],4=>$lang['desc_orchi'],5=>$lang['desc_nani'])
);
$classi=array(
'nome'=>array(1=>$lang['Guerriero'],2=>$lang['Mago'],3=>$lang['Ladro']),
'descrizione'=>array(1=>$lang['desc_guerriero'],2=>$lang['desc_mago'],3=>$lang['desc_ladro']),
'agilita'=>array(1=>70,2=>30,3=>120),
'attfisico'=>array(1=>90,2=>10,3=>40),
'attmagico'=>array(1=>10,2=>50,3=>25),
'diffisica'=>array(1=>90,2=>10,3=>40),
'difmagica'=>array(1=>10,2=>50,3=>25),
'mana'=>array(1=>30,2=>150,3=>50)
);
$sessi=array(
'nome'=>array(0=>$lang['Non_definito'],1=>$lang['Maschio'],2=>$lang['Femmina'])
);
?>